### ISSUE TITLE
Potential leak of `AutofacServiceProvider`

### ISSUE THREAD

**Issue by nblumhardt** [autofac/Autofac.Extensions.DependencyInjection#42] opened 2019-02-20 23:52 UTC
Hi! This might be a bit of a vague question, so apologies in advance if I'm completely off-track.

I've been working on leak detection via _Autofac.Analysis_, and discovered that when ASP.NET Core 2.1 registers the service provider, it doesn't appear to mark it as a singleton. At runtime the `AutofacServiceProvider` instance that's returned is disposable, so AFAIK it'll end up in the `Disposer`'s stack (there may still be only one instance, but entries in the stack will grow).

![image](https://user-images.githubusercontent.com/342712/53133140-ce6f4300-35bd-11e9-9888-39c58fb499ad.png)

It doesn't look like there's any common path in ASP.NET Core that triggers the leak - but it could be a bit of a footgun. Curious whether there's anything I'm missing here..? Using 4.9 and the latest version of this package. Thanks!

**Comment by nblumhardt** [comment] 2019-02-20 23:55
Ah, I see this might have been introduced in the fix for #30. I'm using the new generic container registration API:

```csharp
class Startup
{
...
        public void ConfigureContainer(ContainerBuilder builder)
        {
```

**Comment by tillig** [comment] 2019-02-21 15:59
Yeah, it looks like this is a problem - we register the service provider [at the time we populate services](https://github.com/autofac/Autofac.Extensions.DependencyInjection/blob/36d487749ef7184357bbc4d162bf425b8474eb36/src/Autofac.Extensions.DependencyInjection/AutofacRegistration.cs#L90) because from a service location standpoint, folks want to resolve an `IServiceProvider` and do stuff.

But #30 was all about the heartburn around the root service provider not being disposable, where the Microsoft one, apparently, is. (It's not part of the contract of the conforming container, but don't get me started.)

I think the fix for this will involve:

- Two different service providers - one that is disposable, one that isn't.
- In the service provider factory, which actually builds the container and everything, [return the disposable provider](https://github.com/autofac/Autofac.Extensions.DependencyInjection/blob/36d487749ef7184357bbc4d162bf425b8474eb36/src/Autofac.Extensions.DependencyInjection/AutofacServiceProviderFactory.cs#L74).
- When we register `IServiceProvider` in the container, register the _non-disposable_ one.

From a breaking/API perspective, we need to leave `AutofacServiceProvider` as disposable, but we can create a base class under it, possibly internal, that has all the functionality yet isn't marked disposable.

**Comment by tillig** [comment] 2019-02-21 16:37
Of course, we likely haven't seen this because people resolving `IServiceProvider` are probably doing so in controllers or things that are part of a request lifetime scope, so when the request is over it all gets cleaned up and no leak.

Nevertheless, I have a couple of minutes here and this seems simple; I'll put a PR together you can look at.

**Comment by tillig** [comment] 2019-02-21 17:23
On further investigation, I'm thinking this whole thing is intentional, in as much as it mimics the behavior of the conforming container and the expected/implied behavior that people want.

The [Microsoft DI specification tests assume the service provider your factory returns is disposable](https://github.com/aspnet/Extensions/blob/d349703e08a14e7bcabec0f632bbff55f3c79b87/src/DependencyInjection/DI.Specification.Tests/src/DependencyInjectionSpecificationTests.cs#L678). How the service provider is created for the spec tests [is based on some abstract implementation you provide](https://github.com/aspnet/Extensions/blob/d349703e08a14e7bcabec0f632bbff55f3c79b87/src/DependencyInjection/DI.Specification.Tests/src/DependencyInjectionSpecificationTests.cs#L671). For reference, they currently [run the Autofac tests themselves by just newing up a provider](https://github.com/aspnet/Extensions/blob/d349703e08a14e7bcabec0f632bbff55f3c79b87/src/DependencyInjection/DI.External.Tests/test/Autofac.cs#L12) so it assumes that provider is disposable.

I don't see where they're running the specs on their own container but I would assume the default retrieval for the service provider would be to [build the service provider right off the collection, which just returns a `new ServiceProvider` on their end](https://github.com/aspnet/Extensions/blob/f0458995c6/src/DependencyInjection/DI/src/ServiceCollectionContainerBuilderExtensions.cs#L47). The default `ServiceProvider` [is `IDisposable`](https://github.com/aspnet/Extensions/blob/9b0bb18b33821f2de291556483ed3c9022219c22/src/DependencyInjection/DI/src/ServiceProvider.cs#L13) and there aren't any other providers.

So... yeah, this does seem to be a bit of a footgun. If you resolve an `IServiceProvider` in the default framework it is associated with the current scope and if you dispose it, it will dispose things out from under the other providers in the scope.

```c#
var baseProvider = new ServiceCollection()
  .AddSingleton<DisposeTracker>()
  .BuildServiceProvider();
var tracker = baseProvider.GetService<DisposeTracker>();
Assert.False(tracker.IsDisposed);
var resolvedProvider = baseProvider.GetService<IServiceProvider>();
Assert.NotSame(baseProvider, resolvedProvider);
((IDisposable)resolvedProvider).Dispose();
Assert.True(tracker.IsDisposed);
```

If you resolve a ton of these during a request, they're all disposable and they'll all be held until the scope is disposed. Ostensibly that's at the end of the request, though, so maybe not a big deal. If you are resolving a bunch of `IServiceProvider` instances from the root container then, yeah, it will bite you... but that'll happen with the default container, too, so folks _should_ be expecting that.

Functions as designed-ish?

**Comment by nblumhardt** [comment] 2019-02-21 21:31
Thanks for digging into it @tillig. I think (given the zany design constraints :-)) a "by design" is defensible, but it does seem rather awful.

Since the contract seems to expect that it's okay for consumers to resolve and then dispose a service provider, would it make sense to sneak code in to mark the `AutofacServiceProvider` registration `ExternallyOwned()`, irrespective of how the framework registers it? There wouldn't be any observable behavior difference as far as I can tell, but it would prevent the possible leak.

Not knowing enough about how this all fits together, I can't get a feel for the relative risks of the two behaviors, but if there's anything to do here I'm happy sending whatever PR is needed.

**Comment by tillig** [comment] 2019-02-21 21:40
Yeah, I'm not sure. I really tried reverse engineering how the framework wants to get a reference to the provider vs. what you would expect to do in a per-request/per-scope service location thing and... the hosting mechanism over there now is so complex I just got lost. (Though, admittedly, some of the stuff they do with different DI behaviors, like ILEmit vs. dynamic, etc. is sort of interesting.)

I do know that the framework thinks it's responsible for disposing the root provider... but the consumers of `IServiceProvider` assume that the provider will be disposed for them, whether it's at the root level or in a request.

`ExternallyOwned` may be the way to get around it. Just stop Autofac from tracking it and let other systems - the framework, the user, the service scope - handle the disposal manually. That would at least be reasonably consistent with how lifetime scopes work - you create it, we assume you dispose it. No tracking, no automatic disposal.

**Comment by nblumhardt** [comment] 2019-02-21 21:45
:+1: the `IServiceProvider`/`ILifetimeScope` analogy is pretty good (just very strange that the framework would then expect unique instances, but 🤷‍♂️ ).

**Closed** 2019-02-22 02:56 UTC
